# Generated by Django 5.2.8 on 2026-01-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_bdt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
