# Generated by Django 5.2.8 on 2025-12-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='sourcing.country')),
            ],
        ),
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LOCAL', 'Local'), ('BULK', 'Bulk')], default='LOCAL', max_length=10)),
                ('price_origin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('moq', models.IntegerField(default=1)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.country')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sourcing.seller')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.productvariant')),
            ],
        ),
    ]
