# Generated by Django 5.2.8 on 2026-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('product', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], default='air', max_length=10)),
                ('delivery', models.CharField(choices=[('door', 'Door'), ('pickup', 'Pickup')], default='door', max_length=10)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('QUOTED', 'Quoted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
