# Generated by Django 5.2.8 on 2025-12-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LOCAL', 'Local'), ('BULK', 'Bulk')], max_length=10)),
                ('delivery_type', models.CharField(choices=[('DOOR', 'Door'), ('PICKUP', 'Pickup')], max_length=10)),
                ('min_days', models.IntegerField()),
                ('max_days', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.country')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea')], default='AIR', max_length=10)),
                ('min_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('max_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cost_bdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.country')),
            ],
        ),
    ]
