# Generated by Django 5.2.8 on 2025-12-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate_to_bdt', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LOCAL', 'Local'), ('BULK', 'Bulk')], max_length=10)),
                ('fee_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
